name: asset_delivery
description: "A Flutter plugin for managing on-demand asset delivery with Play Asset Delivery, supporting asset pack setup, progress tracking, and persistent storage."
version: 0.0.1
homepage: https://github.com/mohsen-motlagh/asset_delivery

environment:
  sdk: '>=3.10.0'
  flutter: '>=3.38.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

executables:
  setup_asset_pack: setup_asset_pack
  
flutter:
  plugin:
    platforms:
      android:
        package: com.github.mohsenmotlagh.asset_delivery
        pluginClass: AssetDeliveryPlugin
      ios:
        pluginClass: AssetDeliveryPlugin